Task
friend class Threadmanager
bool Task::running
Referenced by run, stop.
boost::thread* Task::thisThread
Referenced by run, Threadmanager::waitForThreadsToFinish.
SynchronisationBarrier* Task::barrier
Referenced by mainLoop, Task, Threadmanager::willStartThreadOnMe.
int Task::speedFactor
Task::Task()
References barrier, setSynchronisationBarrier.
boost::thread * Task::run()
References mainLoop, running, thisThread, willStartThreadOnMe.
Referenced by Foo::doSomething.
void Task::stop()
References running.
void Task::setSpeedFactor(int factor)
void Task::mainLoop()
References barrier, doStep, SynchronisationBarrier::stepDone, threadWillStart, threadWillStop.
Referenced by run.
virtual bool Task::doStep()=0
Referenced by mainLoop.
void Task::setSynchronisationBarrier(SynchronisationBarrier *barrier)
References SynchronisationBarrier::signIn, SynchronisationBarrier::signOut.
Referenced by Task.
virtual bool Task::willStartThreadOnMe()
Referenced by run.
virtual void Task::threadWillStart()
Referenced by mainLoop.
virtual void Task::threadWillStop()
Referenced by mainLoop.