InformationManager
friend class Destroyer< InformationManager >
InformationManager * InformationManager::instance
Referenced by Instance.
Destroyer< InformationManager > InformationManager::myDestroyer
Referenced by Instance.
std::map<std::string, DataProvider *> InformationManager::offeredData
Referenced by offerData, requestData.
std::map<std::string, std::vector<FeedSubscriber*> > InformationManager::subscribers
Referenced by postDataToFeed, subscribeToFeed, unsubscribeFromFeed.
DataContainer InformationManager::requestData(const DataIdentifier &id, int tries=1)
References Dout, offeredData.
Referenced by Foo::doSomething.
void InformationManager::offerData(DataIdentifier id, DataProvider *provider)
References offeredData.
Referenced by Bar::Bar.
void InformationManager::postDataToFeed(std::string feedName, DataContainer data)
References subscribers.
Referenced by Baz::threadWillStart.
void InformationManager::subscribeToFeed(std::string feedName, FeedSubscriber *subscriber)
References subscribers.
Referenced by Foo::doSomething.
void InformationManager::unsubscribeFromFeed(std::string feedName, FeedSubscriber *subscriber)
References subscribers.
InformationManager * InformationManager::Instance()
References instance, myDestroyer, Destroyer< DOOMED >::SetDoomed.
Referenced by Bar::Bar, Foo::doSomething, Baz::threadWillStart.
InformationManager::InformationManager()
virtual InformationManager::~InformationManager()