SynchronisationBarrier
boost::barrier* SynchronisationBarrier::barrier
Referenced by signIn, signOut, stepDone, SynchronisationBarrier.
unsigned int SynchronisationBarrier::count
Referenced by signIn, signOut, SynchronisationBarrier.
SynchronisationBarrier::SynchronisationBarrier()
References barrier, count.
void SynchronisationBarrier::signIn()
References barrier, count.
Referenced by Task::setSynchronisationBarrier.
void SynchronisationBarrier::signOut()
References barrier, count.
Referenced by Task::setSynchronisationBarrier.
void SynchronisationBarrier::stepDone()
References barrier.
Referenced by Task::mainLoop.