Threadmanager
std::vector<Task *> Threadmanager::myTasks
Referenced by doStep, registerTask, willStartThreadOnMe.
boost::thread_group Threadmanager::myThreads
Referenced by waitForThreadsToFinish, willStartThreadOnMe.
ThreadingMode Threadmanager::threadingMode
Referenced by setThreadingMode, waitForThreadsToFinish, willStartThreadOnMe.
Threadmanager::Threadmanager()
void Threadmanager::registerTask(Task *myTask)
References myTasks.
Referenced by Foo::doSomething.
void Threadmanager::setThreadingMode(ThreadingMode mode)
References threadingMode.
Referenced by Foo::doSomething.
void Threadmanager::waitForThreadsToFinish()
References myThreads, Task::thisThread, THREADING_SEQUENCIAL, threadingMode.
Referenced by Foo::doSomething.
bool Threadmanager::doStep()
References myTasks.
bool Threadmanager::willStartThreadOnMe()
References Task::barrier, myTasks, myThreads, THREADING_FREE_WHEELING, THREADING_LOCK_STEP, threadingMode.